name: Deploy to VPS

on:
  push:
    branches: [ "main", "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/doo/rutr_kino_91_00_parser
            git pull

            docker stop rutr_kino_91_00_parser || true
            docker rm rutr_kino_91_00_parser || true

            docker build -t rutr_kino_91_00_parser .

            docker run -d \
              --name rutr_kino_91_00_parser \
              --network docker-net \
              --restart unless-stopped \
              --env-file .env \
              rutr_kino_91_00_parser